- CMakeLists.txt
- include/poac/subcmd/build.hpp
- include/poac/subcmd/run.hpp
- include/poac/subcmd/test.hpp
- include/poac/util/stroite/core/compiler.hpp
Some environment, `-lboost_filesystem` is not right way to find the library.
> Support Windows

- README.md
> Remove manual build information for cygwin users

- appveyor.yml
> Fix yaml-cpp_dir

- .travis.yml
It was about 10 minutes earlier
> Improve rotation speed of Travis CI

- README.md
TODO: Support submitting report in circleci.
> WIP: Add a Codecov badge to README.md

- .github/workflows/macos.yml
ref: https://github.com/poacpm/poac/pull/360/checks?check_run_id=1655921715
> Remove macos-11.0 because it is broken frequently

- .github/workflows/coverage.yml
ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> Fix coverage CI

- .github/workflows/linux.yml
> Revert "Add clang-11 for linux ci"

- include/poac/cmd/build.hpp
- include/poac/cmd/create.hpp
- include/poac/cmd/init.hpp
- include/poac/core/resolver.hpp
- include/poac/poac.hpp
Closes: https://github.com/poacpm/poac/issues/53
> Support dev-dependencies, which are not propagated to dependents

- include/poac/config.hpp
- include/poac/util/misc.hpp
- include/poac/util/termcolor2/config.hpp
- lib/util/misc.cc
- tests/unit/util/cfg.cc
The `~/.poac` directory will no longer be created.
> Support XDG Base Directories

- .clang-tidy
- .github/workflows/codeql-analysis.yml
- .github/workflows/cpp.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- CMakeLists.txt
- README.md
- include/poac/util/net.hpp
- lib/util/misc.cc
- lib/util/pretty.cc
By default:
* `CMAKE_BUILD_TYPE`: `Debug`
* `CPM_USE_LOCAL_PACKAGES`: `On`
* `POAC_BUILD_TESTING`: `On`
> Refactor GitHub Actions

- lib/core/builder/manifest.cc
Closes https://github.com/poac-dev/poac/issues/760
> Include project headers

- lib/cmd/search.cc
- lib/core/builder/build.cc
- lib/util/net.cc
cf. https://github.com/orgs/poac-dev/discussions/763
> Output `compile_commands.json`

- .github/workflows/codeql.yml
- .github/workflows/cpp.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- Makefile
- README.md
- poac.toml
- src/Algos.cc
- src/Algos.hpp
- src/BuildConfig.cc
- src/Cmd/New.cc
- src/Git/Config.hpp
- src/Git/Describe.hpp
- src/Git/Exception.hpp
- src/Git/Git2.hpp
- src/Git/Global.hpp
- src/Git/Oid.hpp
- src/Git/Repository.hpp
- src/Git/Revparse.hpp
- src/Git/Revwalk.hpp
- src/Manifest.cc
- src/Manifest.hpp
Closes https://github.com/poac-dev/poac/issues/813
> Support system dependencies

- Makefile
- poac.toml
- src/BuildConfig.cc
- src/Manifest.cc
- src/Manifest.hpp
https://github.com/orgs/poac-dev/discussions/829
> Support LTO

- Makefile
- poac.toml
- src/BuildConfig.cc
- src/Manifest.cc
- src/Manifest.hpp
Closes https://github.com/poac-dev/poac/pull/830
> Support CXXFLAGS in poac.toml

- src/Cmd/Version.cc
https://godbolt.org/z/nMj51E7Ws
> Include date in version command

- src/Cmd/Global.cc
- src/Cmd/Global.hpp
- src/main.cc
Closes https://github.com/poac-dev/poac/issues/859
> Implement shorthand for commands

- src/Logger.hpp
- src/main.cc
unfortunately I pulled your updates, so I had to create a whole new pr, but in this one I changed couts to cerr only where needed.
But I couldn't work out how to echo to stderr.
> Use stderr for Logger

- src/Algos.cc
- src/Rustify/Aliases.hpp
https://github.com/poac-dev/poac/issues/953
> Remove Arr alias

- src/Algos.cc
- src/Algos.hpp
- src/BuildConfig.cc
- src/Cli.cc
- src/Cli.hpp
- src/Cmd/Build.cc
- src/Cmd/Lint.cc
- src/Manifest.cc
- src/Manifest.hpp
- src/Rustify/Aliases.hpp
- src/Semver.cc
- src/Semver.hpp
- src/main.cc
- srcOld/Cfg.hpp
- srcOld/Lockfile.hpp
- srcOld/Resolver.hpp
- srcOld/Resolver/Resolve.hpp
- srcOld/Resolver/Sat.hpp
- srcOld/Resolver/Types.hpp
- srcOld/Sha256.hpp
https://github.com/poac-dev/poac/issues/953
> Remove Vec alias

- src/Algos.cc
- src/Algos.hpp
- src/BuildConfig.cc
- src/Cli.hpp
- src/Cmd/Add.cc
- src/Manifest.cc
- src/Manifest.hpp
- src/Rustify/Aliases.hpp
- src/Rustify/Traits.hpp
- src/VersionReq.hpp
- srcOld/Cfg.hpp
- srcOld/Lockfile.hpp
- srcOld/Resolver.hpp
- srcOld/Resolver/Resolve.hpp
- srcOld/Resolver/Types.hpp
https://github.com/poac-dev/poac/issues/953
> Remove Option alias

- src/Algos.hpp
- src/BuildConfig.cc
- src/Cli.hpp
- src/Cmd/Add.cc
- src/Manifest.cc
- src/Rustify/Aliases.hpp
- srcOld/Resolver/Registry.hpp
- srcOld/Resolver/Types.hpp
https://github.com/poac-dev/poac/issues/953
> Remove HashMap alias

- src/BuildConfig.cc
- src/BuildConfig.hpp
- src/Cmd/Add.cc
- src/Cmd/Build.hpp
- src/Manifest.cc
- src/Manifest.hpp
- src/Rustify/Aliases.hpp
- srcOld/Resolver/Resolve.hpp
closes: https://github.com/poac-dev/poac/issues/953
> Remove HashSet alias

- src/Cmd/Fmt.cc
- src/Cmd/Lint.cc
closes #952
Should we add an placeholder to exclude option?
> add exclude option to fmt subcmd

- src/BuildConfig.cc
- src/Cmd/Search.cc
> allow main source file to have not only .cc extension

- src/BuildConfig.cc
refactoring piece of my code a bit
> use path::stem

- .clang-tidy
related to: https://github.com/poac-dev/poac/pull/986
> Enable cert-env33-c check

- src/Algos.cc
- src/Algos.hpp
- src/BuildConfig.cc
- src/BuildConfig.hpp
- src/Cli.cc
- src/Cli.hpp
- src/Cmd/Build.cc
- src/Cmd/Run.cc
- src/Cmd/Search.cc
- src/Cmd/Test.cc
- src/Cmd/Tidy.cc
- src/Command.hpp
- src/Git2/Oid.hpp
- src/Git2/Time.cc
- src/Manifest.cc
- src/Manifest.hpp
- src/Parallelism.cc
- src/Parallelism.hpp
- src/Rustify/Aliases.hpp
- src/Rustify/Tests.hpp
- src/Semver.cc
- src/Semver.hpp
- src/TermColor.cc
- src/TermColor.hpp
- src/VersionReq.cc
- src/VersionReq.hpp
Custom aliases are just confusing to most contributors and this increased the review cost.
> Remove integer aliases

- src/Cmd/Add.cc
- Preserve table orders when adding dependencies to the manifest
- Keep dependency entries as a single line table
> add: preserve dependency order and keep entries in single line

- src/Cmd/New.cc
- src/Cmd/Tidy.cc
fixup for #1026, related #1034
This PR fixes diagnostics broken with #1026.
> logger: catch up with logger::info interface change

- src/Algos.cc
- src/BuildConfig.cc
- src/Command.cc
- src/Command.hpp
> command: avoid stdout/err identifiers

- .github/workflows/cpp.yml
- src/BuildConfig.cc
- src/BuildConfig.hpp
- src/Cmd/Test.cc
- tests/08-test.sh
closes: https://github.com/cabinpkg/cabin/issues/973
> feat(test): support coverage
