- README.md
fixed typo
FYI: Currently there is no .github/CONTRIBUTING.md
> fixed CONTRIBUTING.md

- README.md
関連issue: #93 
TODO: Cygwin上で普通にビルドできるようになったらこのコミットをrevertする．
> Add manual build information for cygwin users

- CMakeLists.txt
- README.md
I was not able to compile the poac on fedora 28 when following the manual install instruction.
However I tried to compile it with the cmake option ` -DCMAKE_CXX_FLAGS="-D_GNU_SOURCE -DBOOST_ASIO_HAS_STD_STRING_VIEW"`, and compile success.
I removes `-Wa,-mbig-obj` from Cygwin version because it causes the error on fedora 28.
boost version is 1.66.0-8, which is the latest version from dnf on fedora 28.
Although this commit is tentative, it might be helpful for some Linux users for now.
> Add manual build information for some Linux users

- README.md
poac is now available in Arch User Repository. (#195)
This request will add a sentence offering AUR distribution of poac to README.md
Installation in Arch Linux can be done with the command like the following.
```console
~ $ yay -S poac
```
> offer AUR distribution of poac to Arch Linux users on README.md

- cmake/AddLibArchive.cmake
- cmake/AddOpenSSL.cmake
> Refactor regexp

- cmake/AddNinja.cmake
The commit hash of `ken-matsui/ninja` is at risk of deleting.
> Revert the commit hash of Ninja

- CMakeLists.txt
- cmake/Helpers.cmake
- lib/cmd/CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/core/builder/compiler/cxx/CMakeLists.txt
- lib/core/builder/compiler/lang/CMakeLists.txt
- lib/core/builder/ninja/CMakeLists.txt
- lib/core/resolver/CMakeLists.txt
- lib/data/CMakeLists.txt
- lib/util/CMakeLists.txt
- lib/util/semver/CMakeLists.txt
- tests/unit/core/CMakeLists.txt
- tests/unit/core/builder/ninja/CMakeLists.txt
- tests/unit/util/CMakeLists.txt
Related to: https://github.com/macports/macports-ports/pull/15429
Libraries of Poac should not be provided since they are not designed to be used by others.
> Avoid providing Poac libraries

- lib/cmd/create.cc
Current `poac` outputs `poac_output` , not `target` . However, `poac create` outputs `.gitignore` for `target` , so this PR fixes this.
> Fix `.gitignore` generated with poac create

- src/main.cc
- suggest subcommand even with flags/options
- see `poac -v seach` , current `poac` doesn't suggest `search`
- stop subcommand suggestion if subcommand is correct
- see `poac search` , current `poac` suggest `search` even though the subcommand is correct
> Fix subcommand suggestion

- include/poac/cmd/build.hpp
- include/poac/cmd/run.hpp
- include/poac/core/validator.hpp
- lib/cmd/build.cc
- lib/cmd/run.cc
- lib/core/validator.cc
- tests/unit/core/validator.cc
This PR adds `--profile` option to `build` and `run` subcommands.
`cargo` has some default profiles, and one of that for developing named `dev` outputs `target/debug/*` .
In this PR I named `debug` for that, but if you mind, it's better to change before merge.
- Q. Why does `valid_profile` return `Result<Option<String>, String>` , 
- instead of `Result<core::builder::ninja::build::Mode, String>` or something like that?
- I don't know the plan, but if `poac` is aspiring to be like `cargo` , `poac` will support user-defined profiles.
- instead of `Result<String, String>` with return value `"debug"` if `valid_profile(None, false)` or `valid_profile(None, None)` ?
- To reuse this function to implement `clean` subcommand. `clean` needs to recognize **unspecified** , `--profile=debug` , and …
> Add --profile Option

- include/poac/cmd/fmt.hpp
- include/poac/cmd/lint.hpp
- include/poac/util/validator.hpp
- lib/cmd/fmt.cc
- lib/cmd/lint.cc
- lib/util/validator.cc
- tests/ui/fmt/no-manifest.stderr
For `fmt` & `lint` commands, when we are inside of a Poac project, Poac executes those commands from the project root wherever we are.
Before this PR:
```console
you:~/hello_world$ poac fmt
Formatting hello_world
you:~/hello_world/build$ poac fmt
Error: required manifest file `poac.toml` does not exist
```
This PR lets:
```console
you:~/hello_world$ poac fmt
Formatting hello_world
you:~/hello_world/build$ poac fmt
Formatting hello_world
```
> Support finding a manifest file in parent directories

- src/BuildConfig.cc
- src/Cmd/Build.cc
- src/Cmd/Clean.cc
- src/Cmd/Global.cc
- src/Cmd/Init.cc
- src/Cmd/New.cc
- src/Cmd/Test.cc
- src/Cmd/Version.cc
- src/Manifest.cc
- src/TermColor.cc
- src/main.cc
reorganizing `#include`s using [IWYU](https://github.com/include-what-you-use/include-what-you-use) except for headers within `Rustify.hpp`
- Note
- `::tolower` and `::toupper` are not guaranteed to be declared in `<cctype>` header, so there are two options:
- **option1**: include `<ctype.h>` instead
- **option2**: rewite those to like `[](auto c) { return std::toupper(c); }`
This PR took **option1** because the purpose of this is just organizing `#include`s.
> reorganize `#include`s

- src/Algos.cc
No time complexity differences because of unordered_map.
> Use contains instead of count for code clarity

- README.md
Hello, first of all I would like to thank you for this great project.
As maintainer of the AUR [poac](https://aur.archlinux.org/packages/poac) package, I think it might be useful for those using an Arch Linux-based distribution to know that they no longer need to manually compile the source code.
Please feel free to suggest improvements to the package if necessary.
> Add installation instructions for Arch Linux based distros

- Makefile
Previously, linker flags were ignored.
This issue was reported by @SunPodder :heart:
> Add linker flags in makefile

- src/Git2/Exception.cc
Fixed for libgit2:1.8.0-2
```
The error functions and enumeration values have been renamed for consistency. The giterr_ functions and values prefix have been renamed to be prefixed with git_error_; similarly, the GITERR_ constants have been renamed to be prefixed with GIT_ERROR_. The old enumerations and macros will be retained for backward compatibility for the foreseeable future.
```
https://github.com/libgit2/libgit2/blob/main/docs/changelog.md
> Fixed for libgit2 1.8

- Makefile
According to current Makefile, acquiring `GIT_DEPS` and building source files are taken to be independent actions.
This often causes an include error in first build (like in CIs).
This PR makes sure that building source files depend on existence of `GIT_DEPS`.
> Fix git dependency (and CI)

- src/Manifest.cc
fixes #927
`Manifest::load()` might throw exceptions, but `Manifest::instance()` calls it unconditionally though it is specified to `noexcept`.
> remove noexcept from `Manifest::instance()`

- Makefile
- src/Manifest.cc
fixes https://github.com/poac-dev/poac/issues/921
> Allow `.` and `++` in dependency names

- src/Git2/Exception.cc
As `git_error_*`s are already declared in `git2` namespace for older versions of libgit2, it's more favorable to use those identifiers than now deprecated ones, I suppose.
Another approach might be to use `git2::git_error_*`s always and make them wrap all changes (like below).
```cpp
namespace git2 {
void
git_error_clear() {
#if ((LIBGIT2_VER_MAJOR < 1) && (LIBGIT2_VER_MINOR < 28)) || ((LIBGIT2_VER_MAJOR >= 1) && (LIBGIT2_VER_MINOR >= 8))
return ::giterr_clear();
#else
return ::git_error_clear();
#endif
}
}
```
> workaround for libgit2 1.8 change (again)

- src/Cmd/Build.cc
allowing option like `poac build -j8`
should we consider `poac build -rj8` as `poac build --release --jobs 8`?
> allow '-jn' style option

- Makefile
Prev: even if dependencies weren't found, Make kept going on.
Now: if dependencies weren't found, Make fails.
> Validate if dependencies exist

- Makefile
- poac.toml
Related to: https://github.com/poac-dev/poac/pull/920, https://github.com/poac-dev/poac/issues/930
This is because they don't follow SemVer.
> Drop libgit2 >=1.9 support

- Makefile
- poac.toml
Running `make && make test` succeeds with fmt 11.0.2.
> Allow usage of fmt 11

- README.md
This PR improves the "Build from source" section of the README slightly:
- Add analogous packages for DNF package manager
- Add installation scripts for each package manager to allow for quick installation of libraries
> Improve building instructions with DNF packages and installation scripts

- .github/workflows/docker.yml
- Dockerfile
Add a Dockerfile to make it easier to contribute to the project with Docker
> Add a Dockerfile for project contributors

- src/BuildConfig.cc
Prior to this patch, -q option was not propagated to the generated Makefile correctly:
```
$ poac b             
Compiling <package name>
Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.83s
$ poac b -q
Compiling <package name>
```
This is because Makefile is generated based on Poac's option and will not reflect the option until it is regenerated.
This patch instead generates Makefile, which takes option info dynamically. Also, this patch avoids printing `Compiling <package name>` when the target is cached.
> Reflect verbosity option changes for Makefile

- src/BuildConfig.cc
fixes https://github.com/poac-dev/poac/issues/924, closes https://github.com/poac-dev/poac/pull/942
> Set Make's default CXX

- src/Cmd/Tidy.cc
Prior to this patch, `poac tidy -fix` finishes every time it finds an error even if all are automatically fixed by `-fix`, so to apply auto fixes to all files, we needed to run the command many times. This patch resolves this problem.
> Keep going when poac tidy -fix

- src/BuildConfig.cc
Added support for environment variables `CXXFLAGS` and `LDFLAGS` while generating makefile.
See https://github.com/poac-dev/poac/issues/923.
> Support reflecting `CXXFLAGS` and `LDFLAGS` environment variables

- poac.toml
- src/Command.cc
Current `poac` code fails `poac lint` with `cpplint` 2.0.0. This PR fixes this:
```console
$ cpplint --version
Cpplint fork (https://github.com/cpplint/cpplint)
cpplint 2.0.0
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
$ poac-out/debug/poac lint --exclude srcOld --exclude testsOld
Linting poac
src/BuildConfig.cc:19:  <filesystem> is an unapproved C++17 header.  [build/c++17] [5]
Done processing src/BuildConfig.cc
src/Command.cc:235:  Add #include <string> for string  [build/include_what_you_use] [4]
Done processing src/Command.cc
src/Command.hpp:4:  <filesystem> is an unapproved C++17 header.  [build/c++17] [5]
Done processing src/Command.hpp
src/Rustify/Aliases.hpp:4:  <filesystem> is an unapproved C++17 header.  [build/c++17] [5]
Done processing src/Rustify/Aliases.hpp …
```
> lint: support cpplint 2.0

- docs/usage.md
usage.md: add an explanation about header-only libraries in the `Install dependencies` section
> usage.md: add an explanation about header-only libs

- cabin.toml
- src/BuildConfig.cc
- src/Manifest.cc
- src/Manifest.hpp
> Build: support always build compdb option

- .github/workflows/cpp.yml
Other C++ CIs require Cabin to be built correctly.  Failing on the build for these CIs can be confusing.
> CI: wait for build-and-test for other C++ CIs

- src/BuildConfig.cc
- src/BuildConfig.hpp
- src/Semver.cc
- src/Semver.hpp
`CABIN_<PKGNAME>_PKG_VERSION_NUM` provides a comparable version number, which is especially useful for library users.
> BuildConfig: support PKG_VERSION_NUM

- src/Algos.cc
- src/Algos.hpp
- src/Cmd/Build.cc
- src/Cmd/Fmt.cc
- src/Cmd/Lint.cc
- src/Cmd/Run.cc
- src/Cmd/Test.cc
- src/Cmd/Tidy.cc
- src/Command.cc
- src/Command.hpp
- src/Manifest.hpp
- src/Rustify/Tests.hpp
This patch fixes an issue where test command ignores test failures due to the incorrect exit status handling.  This patch includes some interface improvements as well.
> Test: fix ignoring test failures

- Makefile
- cabin.toml
- docs/usage.md
- src/Cabin.cc
- src/Cmd.hpp
- src/Cmd/Remove.cc
- src/Cmd/Remove.hpp
- src/Rustify/Result.hpp
- tests/07-remove.sh
Remove project dependencies from cabin.toml
closes #1074
> Cmd: add subcommand `remove`
